saved_model_schema_version: 1
meta_graphs {
  meta_info_def {
    stripped_op_list {
      op {
        name: "Const"
        output_arg {
          name: "output"
          type_attr: "dtype"
        }
        attr {
          name: "value"
          type: "tensor"
        }
        attr {
          name: "dtype"
          type: "type"
        }
      }
      op {
        name: "Placeholder"
        output_arg {
          name: "output"
          type_attr: "dtype"
        }
        attr {
          name: "dtype"
          type: "type"
        }
        attr {
          name: "shape"
          type: "shape"
          default_value {
            shape {
              unknown_rank: true
            }
          }
        }
      }
      op {
        name: "StringJoin"
        input_arg {
          name: "inputs"
          type: DT_STRING
          number_attr: "N"
        }
        output_arg {
          name: "output"
          type: DT_STRING
        }
        attr {
          name: "N"
          type: "int"
          has_minimum: true
          minimum: 1
        }
        attr {
          name: "separator"
          type: "string"
          default_value {
            s: ""
          }
        }
      }
    }
    tags: "serve"
    tensorflow_version: "1.4.0"
    tensorflow_git_version: "v1.4.0-rc1-11-g130a514"
  }
  graph_def {
    node {
      name: "Placeholder"
      op: "Placeholder"
      attr {
        key: "_output_shapes"
        value {
          list {
            shape {
              unknown_rank: true
            }
          }
        }
      }
      attr {
        key: "dtype"
        value {
          type: DT_STRING
        }
      }
      attr {
        key: "shape"
        value {
          shape {
            unknown_rank: true
          }
        }
      }
    }
    node {
      name: "Placeholder_1"
      op: "Placeholder"
      attr {
        key: "_output_shapes"
        value {
          list {
            shape {
              unknown_rank: true
            }
          }
        }
      }
      attr {
        key: "dtype"
        value {
          type: DT_STRING
        }
      }
      attr {
        key: "shape"
        value {
          shape {
            unknown_rank: true
          }
        }
      }
    }
    node {
      name: "StringJoin/inputs_0"
      op: "Const"
      attr {
        key: "_output_shapes"
        value {
          list {
            shape {
            }
          }
        }
      }
      attr {
        key: "dtype"
        value {
          type: DT_STRING
        }
      }
      attr {
        key: "value"
        value {
          tensor {
            dtype: DT_STRING
            tensor_shape {
            }
            string_val: "Input1: "
          }
        }
      }
    }
    node {
      name: "StringJoin/inputs_2"
      op: "Const"
      attr {
        key: "_output_shapes"
        value {
          list {
            shape {
            }
          }
        }
      }
      attr {
        key: "dtype"
        value {
          type: DT_STRING
        }
      }
      attr {
        key: "value"
        value {
          tensor {
            dtype: DT_STRING
            tensor_shape {
            }
            string_val: "!"
          }
        }
      }
    }
    node {
      name: "StringJoin"
      op: "StringJoin"
      input: "StringJoin/inputs_0"
      input: "Placeholder"
      input: "StringJoin/inputs_2"
      attr {
        key: "N"
        value {
          i: 3
        }
      }
      attr {
        key: "_output_shapes"
        value {
          list {
            shape {
              unknown_rank: true
            }
          }
        }
      }
      attr {
        key: "separator"
        value {
          s: ""
        }
      }
    }
    node {
      name: "StringJoin_1/inputs_0"
      op: "Const"
      attr {
        key: "_output_shapes"
        value {
          list {
            shape {
            }
          }
        }
      }
      attr {
        key: "dtype"
        value {
          type: DT_STRING
        }
      }
      attr {
        key: "value"
        value {
          tensor {
            dtype: DT_STRING
            tensor_shape {
            }
            string_val: "Input2: "
          }
        }
      }
    }
    node {
      name: "StringJoin_1/inputs_2"
      op: "Const"
      attr {
        key: "_output_shapes"
        value {
          list {
            shape {
            }
          }
        }
      }
      attr {
        key: "dtype"
        value {
          type: DT_STRING
        }
      }
      attr {
        key: "value"
        value {
          tensor {
            dtype: DT_STRING
            tensor_shape {
            }
            string_val: "!"
          }
        }
      }
    }
    node {
      name: "StringJoin_1"
      op: "StringJoin"
      input: "StringJoin_1/inputs_0"
      input: "Placeholder_1"
      input: "StringJoin_1/inputs_2"
      attr {
        key: "N"
        value {
          i: 3
        }
      }
      attr {
        key: "_output_shapes"
        value {
          list {
            shape {
              unknown_rank: true
            }
          }
        }
      }
      attr {
        key: "separator"
        value {
          s: ""
        }
      }
    }
    versions {
      producer: 24
    }
  }
  signature_def {
    key: "serving_default"
    value {
      inputs {
        key: "i1"
        value {
          name: "Placeholder:0"
          dtype: DT_STRING
          tensor_shape {
            unknown_rank: true
          }
        }
      }
      inputs {
        key: "i2"
        value {
          name: "Placeholder_1:0"
          dtype: DT_STRING
          tensor_shape {
            unknown_rank: true
          }
        }
      }
      outputs {
        key: "o1"
        value {
          name: "StringJoin:0"
          dtype: DT_STRING
          tensor_shape {
            unknown_rank: true
          }
        }
      }
      outputs {
        key: "o2"
        value {
          name: "StringJoin_1:0"
          dtype: DT_STRING
          tensor_shape {
            unknown_rank: true
          }
        }
      }
      method_name: "tensorflow/serving/predict"
    }
  }
}
