#' @import jsonlite
swagger_from_graph <- function(graph) {
  def <- c(
    swagger_header(),
    swagger_paths(graph),
    swagger_defs()
  )

  jsonlite::toJSON(def)
}

swagger_header <- function() {
  list(
    swagger = unbox("2.0"),
    info = list(
      description = unbox("REST API to TensorFlow Model generated by tfserve."),
      version = unbox("1.0.0"),
      title = unbox("TensorFlow Model")
    ),
    host = unbox("127.0.0.1"),
    basePath = unbox("/api"),
    schemes = list(
      unbox("http")
    )
  )
}

swagger_path <- function(tensor_name, tensor_id) {
  list(
    post = list(
      summary = unbox(paste0("Perform prediction over the '", tensor_name, "' model.")),
      description = unbox(""),
      consumes = list(
        unbox("application/json")
      ),
      produces = list(
        unbox("application/json")
      ),
      parameters = list(
        list(
          "in" = unbox("body"),
          name = unbox("body"),
          description = unbox("Input tensor(s)."),
          required = unbox(TRUE),
          schema = list(
            "$ref" = unbox("#/definitions/Tensor")
          )
        )
      ),
      responses = list(
        "200" = list(
          description = unbox("Success")
        )
      )
    )
  )
}

swagger_paths <- function(graph) {
  path_names <- graph$keys()
  path_values <- lapply(seq_along(path_names), function(path_index) {
    swagger_path(path_names[[path_index]], path_index)
  })

  full_urls <- paste0("/predict/", path_names)

  names(path_values) <- full_urls

  list(
    paths = path_values
  )
}

swagger_defs <- function() {
  list(
    definitions = list(
      Tensor = list(
        type = unbox("object"),
        required = list(
          unbox("input")
        ),
        properties = list(
          input = list(
            type = unbox("integer"),
            format = unbox("int64")
          )
        )
      )
    )
  )
}
