#' @import jsonlite
swagger_from_graph <- function() {
  def <- c(
    swagger_header(),
    swagger_paths(),
    swagger_defs()
  )

  jsonlite::toJSON(def)
}

swagger_header <- function() {
  list(
    swagger = unbox("2.0"),
    info = list(
      description = unbox("REST API to TensorFlow Model generated by tfserve."),
      version = unbox("1.0.0"),
      title = unbox("TensorFlow Model")
    ),
    host = unbox("127.0.0.1"),
    basePath = unbox("/api"),
    schemes = list(
      "http"
    )
  )
}

swagger_paths <- function() {
  list(
    paths = list(
      "/predict" = list(
        post = list(
          summary = unbox("Perform prediction over the model."),
          description = unbox(""),
          consumes = list(
            "application/json"
          ),
          produces = list(
            "application/json"
          ),
          parameters = list(
            "in" = unbox("body"),
            name = unbox("body"),
            description = unbox("Input tensors."),
            required = unbox(TRUE),
            schema = list(
              "$ref" = unbox("#/definitions/Tensor")
            )
          ),
          responses = list(
            "200" = list(
              description = unbox("Success")
            )
          )
        )
      )
    )
  )
}

swagger_defs <- function() {
  list(
    definitions = list(
      Tensor = list(
        type = unbox("object"),
        required = list(
          "input"
        ),
        properties = list(
          input = list(
            type = unbox("integer"),
            format = unbox("int64")
          )
        )
      )
    )
  )
}
